version: '3'

services:

  base:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-common:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-common

  namenode:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-hdfs-namenode:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-hdfs-namenode
    depends_on:
      - base

  datanode:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-hdfs-datanode:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-hdfs-datanode
    depends_on:
      - base

  resourcemanager:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-yarn-resourcemanager:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-yarn-resourcemanager
    depends_on:
      - base

  nodemanager:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-yarn-nodemanager:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-yarn-nodemanager
    depends_on:
      - base

  jobhistoryserver:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-mapred-jobhistoryserver:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-mapred-jobhistoryserver
    depends_on:
      - base

  clientnode:
    image: ${DOCKER_ORG:-packet23}/${DOCKER_PREFIX:-}hadoop-client:${DOCKER_HADOOP_VERSION:-local}
    build: ./hadoop-client
    depends_on:
      - base
